
# Social links (optional)
github_username: JoeTheDeveloper96
linkedin_username: JoeGrantx

# Build settings
markdown: kramdown
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
