# Site settings
description: A modern, clean website for showcase purposes!
author: Joe Grant
email: Joe.Grant109@icloud.com

# Social links (optional)
github_username: JoeTheDeveloper96
linkedin_username: JoeGrantx

# Build settings
markdown: kramdown
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
